language: node_js

node_js:
  - stable

install:
  - npm install

script:
  - npm run test -- --coverage
  
deploy:
  github_token: $github_token
  coveralls_repo_token: $coveralls_repo_token

after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
